---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: kustomize/openshift-gitops/config
    repoURL: 'https://github.com/Caseraw/demo-argocd.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
