---
kind: Secret
apiVersion: v1
metadata:
  name: openshift-gitops-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "1"
data:
  project: ZGVtby1hcHBz
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL0Nhc2VyYXcvZGVtby1hcmdvY2QuZ2l0
type: Opaque
