---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - resources/gitopsservice.yaml
- resources/argocd.yaml
- resources/application.yaml

patches:
- target:
    kind: ArgoCD
    name: openshift-gitops
  patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: ArgoCD
    metadata:
      name: openshift-gitops
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      server:
        route:
          enabled: true
          tls:
            insecureEdgeTerminationPolicy: Redirect
            termination: reencrypt
          wildcardPolicy: None
