---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../install
- resources/secret.yaml
- resources/clusterrole.yaml
- resources/clusterrolebinding.yaml
# - resources/gitopsservice.yaml
- resources/argocd.yaml
- resources/application.yaml

patches:
- target:
    kind: ArgoCD
    name: openshift-gitops
  patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: ArgoCD
    metadata:
      name: openshift-gitops
      namespace: openshift-gitops
    spec:
      server:
        route:
          enabled: true
        tls:
          insecureEdgeTerminationPolicy: Redirect
          termination: passthrough
        wildcardPolicy: None
